version: 0.2
phases:
  install: 
    runtime-versions:
      golang: 1.18
  build:
    commands:
      - go get -u github.com/aws/aws-sdk-go/...
      - touch file.txt
      - ls
      - go run crud.go
artifacts:
  files:
      - '**/*'
