version: 0.2
phases:
  install: 
    runtime-versions:
      golang: 1.18
  build:
    commands:
      - cd crudapp
      - go get -u github.com/aws/aws-sdk-go/...
      - go build main.go
artifacts:
  files:
      - '**/*'
